---
# tasks file for dnsmasq
 - name: Install package
   yum:
     name: "dnsmasq"
     state: latest


# For real systems only
 - name: start service
   service:
     name: "dnsmasq"
     state: started
     enabled: yes
   when: molecule_yml is not defined


 - name: Configure dnsmasq
   template:
     src: dnsmasq.j2   
     dest: /etc/dnsmasq.conf
     backup: true
     mode: '0600'
   notify: restart_dnsmasq




